### ISSUE TITLE
When I use it in Listview.builder() then scrollable it will change data to initial even if we select change ready. Please help check it

### ISSUE THREAD

**Issue by Kimsoer** [salim-lachdhaf/searchable_dropdown#156] opened 2021-05-02 17:15 UTC
When I use it in Listview.builder() then scrollable it will change data to initial even if we select change ready. Please help check it

                      Container(
                        height: 40,
                        width: 160,
                        padding: const EdgeInsets.only(left: 20, right: 20),
                        child: DropdownSearch<String>(
                          mode: Mode.MENU,
                          showSelectedItem: true,
                          dropdownSearchDecoration: InputDecoration(
                            contentPadding: const EdgeInsets.only(left: 40),
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(30),
                              borderSide:
                                  const BorderSide(color: Colors.black12),
                            ),
                          ),
                          items: List.generate(50, (index) => "${index + 1}"),
                          onChanged: (value) {
                          },
                          selectedItem: "1",
                        ),
                      )

**Comment by brunofuhr** [comment] 2021-05-05 19:17
I'm having the same issue.. noticed that flutter isn't calling the 'didUpdateWidget' from the component

**Comment by brunofuhr** [comment] 2021-05-05 21:29
I fixed this by setting the length of ListView.builder to 1 and returning a Column:

`ListView.builder(
  itemCount: 1,
  itemBuilder: (_, index) {
    return Column(
      children: [DropdownSearch<String>(...`


Then the selected value has not changed to the initial value.

**Comment by vasilich6107** [comment] 2021-05-22 18:12
@Kimsoer @brunofuhr you issue could be fixed with `AutomaticKeepAliveClientMixin`
Just create a `Statefull` wrapper witdget over `DropdownSearch`

Read this https://stackoverflow.com/questions/52541172/flutter-listview-keepalive-after-some-scroll

**Comment by salim-lachdhaf** [comment] 2021-05-22 19:20
@Kimsoer it's a normal behavier caused by `List.Builder`. use @vasilich6107 solution's

**Closed by salim-lachdhaf** 2021-05-22 19:20 UTC
