### ISSUE TITLE
"Multiple widgets used the same GlobalKey." when trying to open dropdown with Focus

### ISSUE THREAD

**Issue by Maczuga** [salim-lachdhaf/searchable_dropdown#540] opened 2023-02-01 15:14 UTC
**Describe the bug**
If you wrap DropdownSearch with Focus widget and try to open the dropdown with dropdownKey during onFocusChange event on that focus (for example by pressing "next" button on android keyboard when focused on previous input) - crash occurrs:

"The key [LabeledGlobalKey<SelectionWidgetState<int>>#e6271] was used by multiple widgets. The parents of those widgets were different widgets that both had the following description:
  DefaultTextStyle(debugLabel: (englishLike bodyMedium 2014).merge(blackMountainView bodyMedium), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
A GlobalKey can only be specified on one widget at a time in the widget tree.".

**To Reproduce**
1. Press TextFormField labeled: "Press me and then 'next' action on the keyboard"
2. See the error in console

Also link to a simple repo with repro: https://github.com/Maczuga/searchable_dropdown_bug

**Expected behavior**
Error should not occur and the dropdown should be opened without issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/544349/216080141-e48d37ff-01a3-4fec-a1ce-557d1ea5f36a.png)

**Smartphone (please complete the following information):**
 - Device: Android Emulator
 - OS: Android 12
 - Browser: n/a
 - Version: n/a

**Comment by WhiteHatTux** [comment] 2023-11-24 17:01
I am experiencing the same issue, but it turns out that this happens, because the openDropdownSearch() is called multiple times. 
Extending your onFocusChange like this:
```
      onFocusChange: (hasFocus) {
        if (hasFocus && dropdownKey.currentState?.isFocused == false) {
          dropdownKey.currentState?.openDropDownSearch();
          print("Opening dropdown search");
        }
      },```
fixes the issue partially. 
I say partially, because it will still create this error when you dismiss the dropdown (on the web with escape key). 
I'll update once I find the solution for the closing of the dropdown.

**Comment by salim-lachdhaf** [comment] 2024-09-14 21:35
thank you for reporting that, i tried to reproduce that with the last version v6.0.0 but without success, could please check if you still have the issue ?

**Comment by salim-lachdhaf** [comment] 2024-09-17 15:13
Thnx @WhiteHatTux.

@Maczuga the issue is not coming from the lib it self, but from the `Focus`  widget which calls `onFocusChange `multiple times as @WhiteHatTux  said.

You have to adjust your code to prevent this issue, please check @WhiteHatTux propositions.

**Closed by salim-lachdhaf** 2024-09-17 15:13 UTC
